"""Fetch everything the desktop app needs to run, on demand, from pinned sources.

A source checkout cannot run on its own. ``models/`` and ``tools/`` are gitignored, so a
fresh clone is missing three things, and each one breaks the app differently:

  * the llama.cpp runtime (``tools/llama/llama-server.exe`` + DLLs) - without it the VLM
    cannot start at all, whatever weights are present;
  * MobileCLIP-S2 - without it the embedder does not fail, it quietly falls back to
    ``clip-ViT-B-32``, a different embedding space, so an existing index returns
    nonsense with no error; and otherwise open_clip fetches it on first use into
    ``~/.cache``, outside the project, with no progress shown;
  * the VLM weights for the active profile (2.3-3.3 GB).

All three are listed in ``config/model_manifest.json`` (regenerated by
``scripts/gen_model_manifest.py``) with an exact size and SHA-256, and every URL is
pinned: HuggingFace files to a commit, llama.cpp to a release build. So what lands on
disk is byte-for-byte what was validated, not whatever upstream serves today.

Everything is written under the project root, so deleting the project folder removes it
all. Files already sitting in the HuggingFace cache are copied rather than re-fetched -
the checksum still decides whether they are accepted.

Downloads resume with HTTP Range. A short ``.part`` file is treated as an interrupted
transfer and kept; it is only deleted when it is full-length and fails its checksum.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import threading
import urllib.request
import zipfile
from pathlib import Path
from typing import Callable, Dict, List, Optional

_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent


def base_url(explicit: Optional[str] = None) -> str:
    """Resolve the model server root: explicit arg > env > config.yaml > empty."""
    if explicit:
        return explicit.rstrip("/")
    env = os.environ.get("VIDEORAG_MODEL_BASE_URL", "").strip()
    if env:
        return env.rstrip("/")
    try:
        import yaml  # PyYAML is already a dependency
        cfg = yaml.safe_load((_PROJECT_ROOT / "config" / "config.yaml").read_text())
        url = ((cfg or {}).get("models", {}) or {}).get("download_base_url", "")
        if url:
            return str(url).rstrip("/")
    except Exception:
        pass
    return ""


def fetch_manifest(url: Optional[str] = None) -> dict:
    """The manifest shipped in config/, or a remote copy if a base URL is configured.

    Most entries point straight at HuggingFace or GitHub, so shipping the manifest means
    there is nothing to host at all. A base URL is only needed to repoint an installed
    copy without regenerating it.
    """
    root = base_url(url)
    if root:
        with urllib.request.urlopen(f"{root}/manifest.json", timeout=30) as r:
            return json.loads(r.read().decode("utf-8"))
    local = _PROJECT_ROOT / "config" / "model_manifest.json"
    if not local.is_file():
        raise RuntimeError(
            "No model manifest. Run scripts/gen_model_manifest.py, or set "
            "models.download_base_url / VIDEORAG_MODEL_BASE_URL to fetch one."
        )
    return json.loads(local.read_text())


def _entry_url(entry: dict, root: str) -> str:
    """Absolute 'url' (current form) or 'path' relative to the base URL (older form)."""
    if entry.get("url"):
        return entry["url"]
    return f"{root}/{entry['path']}"


def profile_entries(profile: str, url: Optional[str] = None) -> List[dict]:
    """Everything needed to run [profile]: the runtime, shared weights, then its own VLM.

    Ordered smallest-blast-radius first, so a partial download still leaves the app
    more usable than before rather than less.
    """
    man = fetch_manifest(url)
    win = man.get("windows", {})
    if profile not in win:
        raise RuntimeError(f"profile '{profile}' not in manifest (have: {list(win)})")
    return list(win.get("runtime", [])) + list(win.get("common", [])) + list(win[profile])


def _is_archive(entry: dict) -> bool:
    """A zip that is unpacked into a directory rather than kept as a file."""
    return bool(entry.get("extract_to"))


def _label(entry: dict) -> str:
    return entry.get("label") or Path(entry["dest"]).name


def _present(entry: dict) -> bool:
    if _is_archive(entry):
        # The zip is deleted once unpacked, so judge by what it installs.
        return (_PROJECT_ROOT / entry["provides"]).is_file()
    p = _PROJECT_ROOT / entry["dest"]
    return p.is_file() and p.stat().st_size == entry["bytes"]


def _substitute(entry: dict) -> bool:
    """A weight already sitting at this path, but not the build the manifest names.

    Not the same thing as a broken download. A partial transfer lives in a `.part`
    file and is only renamed into place after its SHA-256 matches, so a full-sized
    file at the destination with the wrong length is something the user put there -
    a local quantisation, or an upstream build that has since been re-uploaded.

    Treating that as "missing" would re-download gigabytes and overwrite weights the
    user's setup was actually validated against, which is how a working install
    quietly turns into an unverified one. So it counts as usable, and is reported
    separately rather than replaced.

    Archives never count: their presence is already judged by the file they install,
    so an existing runtime of a different build is left alone by _present() instead.
    """
    if _is_archive(entry):
        return False
    p = _PROJECT_ROOT / entry["dest"]
    return p.is_file() and p.stat().st_size not in (0, entry["bytes"])


def status(profile: str, url: Optional[str] = None) -> dict:
    """Which of the active profile's requirements are present vs missing."""
    try:
        entries = profile_entries(profile, url)
    except Exception as exc:
        return {"configured": False, "error": str(exc),
                "present": [], "missing": [], "ready": False}
    present = [e for e in entries if _present(e)]
    subs = [e for e in entries if not _present(e) and _substitute(e)]
    missing = [e for e in entries if not _present(e) and not _substitute(e)]
    return {
        "configured": True,
        "profile": profile,
        "ready": len(missing) == 0,
        "present": [e["dest"] for e in present],
        "substitutes": [e["dest"] for e in subs],
        "missing": [{"dest": e["dest"], "name": _label(e), "bytes": e["bytes"]}
                    for e in missing],
        "missing_bytes": sum(e["bytes"] for e in missing),
    }


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


# ── re-use what the HuggingFace cache already holds ──────────────────────────────────
_HF_RESOLVE = re.compile(r"^https://huggingface\.co/([^/]+)/([^/]+)/resolve/([^/]+)/(.+)$")


def _hf_cache_file(url: str) -> Optional[Path]:
    """The same file in the local HuggingFace hub cache, if a previous run fetched it.

    open_clip, transformers and huggingface-cli all populate this cache, so on a machine
    that has run the embedder even once, the 398 MB MobileCLIP checkpoint is already on
    disk. Copying it is seconds; fetching it again is minutes. The copy is still
    checksummed like any download, so a stale or different revision is rejected.
    """
    m = _HF_RESOLVE.match(url)
    if not m:
        return None
    org, repo, rev, fname = m.groups()
    hub = os.environ.get("HF_HUB_CACHE") or os.environ.get("HUGGINGFACE_HUB_CACHE")
    hub_dir = Path(hub) if hub else Path(
        os.environ.get("HF_HOME", str(Path.home() / ".cache" / "huggingface"))) / "hub"
    snaps = hub_dir / f"models--{org}--{repo}" / "snapshots"
    for cand in [snaps / rev / fname, *sorted(snaps.glob(f"*/{fname}"))]:
        try:
            if cand.is_file():
                return cand.resolve()   # snapshot entries are symlinks into blobs/
        except OSError:
            continue
    return None


# ── shared progress state so an HTTP caller can poll a background download ──────────
_STATE: Dict[str, object] = {"running": False, "profile": None, "index": 0, "total": 0,
                             "name": "", "phase": "", "file_done": 0, "file_bytes": 0,
                             "error": None, "done": False, "cancelled": False}
_LOCK = threading.Lock()
_CANCEL = threading.Event()


class DownloadCancelled(Exception):
    """Raised inside the transfer loop when the user presses Stop."""


def get_state() -> dict:
    with _LOCK:
        return dict(_STATE)


def cancel() -> bool:
    """Ask the running download to stop. Partial files are kept so it can resume."""
    with _LOCK:
        running = bool(_STATE.get("running"))
    if running:
        _CANCEL.set()
    return running


def _copy_with_progress(src: Path, dst: Path, on_bytes: Callable[[int], None]) -> None:
    done = 0
    with open(src, "rb") as fi, open(dst, "wb") as fo:
        while True:
            if _CANCEL.is_set():
                raise DownloadCancelled()
            buf = fi.read(1 << 22)
            if not buf:
                break
            fo.write(buf)
            done += len(buf)
            on_bytes(done)


def _transfer(src_url: str, part: Path, expected: int, name: str,
              on_bytes: Callable[[int], None]) -> None:
    """Bring [part] up to [expected] bytes, resuming from wherever it stopped."""
    have = part.stat().st_size if part.is_file() else 0
    if have > expected:
        part.unlink()
        have = 0

    if have == 0:
        cached = _hf_cache_file(src_url)
        if cached is not None and cached.stat().st_size == expected:
            _copy_with_progress(cached, part, on_bytes)
            return

    if have < expected:
        req = urllib.request.Request(src_url, headers={"User-Agent": "VideoRAG-downloader"})
        if have:
            req.add_header("Range", f"bytes={have}-")
        with urllib.request.urlopen(req, timeout=60) as resp:
            # 200 means the server ignored the Range; restart from zero.
            mode = "ab"
            if have and resp.status == 200:
                have = 0
                mode = "wb"
            with open(part, mode) as out:
                done = have
                while True:
                    if _CANCEL.is_set():
                        raise DownloadCancelled()
                    buf = resp.read(1 << 16)
                    if not buf:
                        break
                    out.write(buf)
                    done += len(buf)
                    on_bytes(done)

    # A dropped connection ends the stream exactly like a finished one - read() returns
    # b"" either way. This used to fall straight through to the checksum, fail it, and
    # DELETE the partial file: a gigabyte of resumable progress thrown away, restarted
    # from zero on the next attempt. Short means interrupted; keep it and say so.
    size = part.stat().st_size if part.is_file() else 0
    if size < expected:
        raise RuntimeError(
            f"Connection interrupted at {size // 1_000_000} of {expected // 1_000_000} MB "
            f"for {name}. Press Download again to resume from there.")


def _extract(zip_path: Path, target: Path) -> None:
    """Unpack into [target] through a staging directory, refusing any path escape."""
    staging = target.parent / (target.name + ".staging")
    if staging.exists():
        shutil.rmtree(staging)
    with zipfile.ZipFile(zip_path) as z:
        files = [i for i in z.infolist() if not i.is_dir()]
        names = [i.filename for i in files]
        # Some archives wrap everything in one top-level folder; flatten it so the
        # binaries land directly in the target, where the server looks for them.
        tops = {n.split("/", 1)[0] for n in names}
        strip = (next(iter(tops)) + "/") if (len(tops) == 1 and all("/" in n for n in names)) else ""
        root = staging.resolve()
        for info in files:
            rel = info.filename[len(strip):]
            out = (staging / rel).resolve()
            if root not in out.parents:
                raise RuntimeError(f"Refusing unsafe path in archive: {info.filename}")
            out.parent.mkdir(parents=True, exist_ok=True)
            with z.open(info) as src, open(out, "wb") as dst:
                shutil.copyfileobj(src, dst, 1 << 20)
    target.mkdir(parents=True, exist_ok=True)
    for f in sorted(staging.rglob("*")):
        if f.is_file():
            d = target / f.relative_to(staging)
            d.parent.mkdir(parents=True, exist_ok=True)
            os.replace(f, d)
    shutil.rmtree(staging, ignore_errors=True)


def _fetch_entry(entry: dict, root: str, on_bytes: Callable[[int], None],
                 on_phase: Callable[[str], None]) -> None:
    dest = _PROJECT_ROOT / entry["dest"]
    dest.parent.mkdir(parents=True, exist_ok=True)
    part = dest.with_suffix(dest.suffix + ".part")
    name = _label(entry)

    on_phase("download")
    _transfer(_entry_url(entry, root), part, entry["bytes"], name, on_bytes)

    sha = (entry.get("sha256") or "").lower()
    if sha:
        on_phase("verify")
        if _sha256(part) != sha:
            # Full length but wrong bytes: genuinely corrupt, so this one does go.
            part.unlink(missing_ok=True)
            raise RuntimeError(f"{name} failed its checksum and was deleted; press Download to retry.")

    if _is_archive(entry):
        on_phase("extract")
        _extract(part, _PROJECT_ROOT / entry["extract_to"])
        part.unlink(missing_ok=True)   # the zip has served its purpose
    else:
        os.replace(part, dest)


def _space_needed(todo: List[dict]) -> int:
    """Bytes still to be written, with headroom for unpacking archives."""
    need = 0
    for e in todo:
        part = (_PROJECT_ROOT / e["dest"]).with_suffix(Path(e["dest"]).suffix + ".part")
        have = part.stat().st_size if part.is_file() else 0
        need += max(0, e["bytes"] - have)
        if _is_archive(e):
            need += 2 * e["bytes"]   # unpacked size; the llama.cpp zips expand ~1.7x
    return need


def download_profile(profile: str, url: Optional[str] = None,
                     on_progress: Optional[Callable[[dict], None]] = None,
                     force: bool = False) -> None:
    """Download everything missing for [profile]; updates module progress state.

    Weights already on disk under a different build are left alone unless [force],
    so running this never silently swaps out a model the setup was validated with.
    """
    root = base_url(url)
    entries = profile_entries(profile, url)
    missing = [e for e in entries
               if not _present(e) and (force or not _substitute(e))]

    _CANCEL.clear()
    with _LOCK:
        _STATE.update(running=True, profile=profile, total=len(missing), index=0,
                      name="", phase="", file_done=0, file_bytes=0, error=None,
                      done=False, cancelled=False)
    try:
        # Check space before the first byte. A nearly full disk otherwise fails partway
        # through a multi-gigabyte file, after a long wait, with whatever OSError the
        # write happens to raise.
        need = _space_needed(missing)
        free = shutil.disk_usage(_PROJECT_ROOT).free
        if missing and free < need + (256 << 20):
            raise RuntimeError(
                f"Not enough disk space: about {need / 1e9:.1f} GB needed, "
                f"{free / 1e9:.1f} GB free on {_PROJECT_ROOT.anchor}. "
                "Free some space and press Download again - nothing has been lost.")

        for i, e in enumerate(missing):
            with _LOCK:
                _STATE.update(index=i, name=_label(e), phase="download",
                              file_done=0, file_bytes=e["bytes"])

            def _on_bytes(done: int) -> None:
                with _LOCK:
                    _STATE.update(file_done=done)
                if on_progress:
                    on_progress(get_state())

            def _on_phase(phase: str) -> None:
                with _LOCK:
                    _STATE.update(phase=phase)

            _fetch_entry(e, root, _on_bytes, _on_phase)
        with _LOCK:
            _STATE.update(running=False, done=True, phase="")
    except DownloadCancelled:
        with _LOCK:
            _STATE.update(running=False, cancelled=True, phase="",
                          error=None)
        raise
    except Exception as exc:
        with _LOCK:
            _STATE.update(running=False, phase="", error=str(exc))
        raise


def start_background(profile: str, url: Optional[str] = None,
                     on_done: Optional[Callable[[], None]] = None) -> bool:
    """Kick off a download in a daemon thread. Returns False if one is already running.

    [on_done] runs only after a complete, verified download - it is how the server
    brings the VLM up without asking the user to restart the app.
    """
    with _LOCK:
        if _STATE.get("running"):
            return False
        _STATE.update(running=True, error=None, done=False, cancelled=False)
    threading.Thread(target=lambda: _safe(profile, url, on_done), daemon=True).start()
    return True


def _safe(profile: str, url: Optional[str], on_done: Optional[Callable[[], None]]) -> None:
    try:
        download_profile(profile, url)
    except Exception:
        return  # recorded in _STATE (error, or cancelled)
    if on_done:
        try:
            on_done()
        except Exception as exc:
            with _LOCK:
                _STATE.update(error=f"Downloaded, but the model failed to start: {exc}")
